apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fast-api-k8s-helm.fullname" . }}
  labels:
    {{- include "fast-api-k8s-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fast-api-k8s-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fast-api-k8s-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fast-api-k8s-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - volumeMounts:
          - mountPath: "/var/tmp/tls_certficatekeyfile.pem"
            name: tls_certificates
            readOnly: true
          env:
          - 
            name: DB_NAME
            value: "{{.Values.db.db_name}}"
          - 
            name: DB_COLLECTION
            value: "{{.Values.db.db_collection}}"
          - 
            name: MONGO_DB_URL
            value: "{{.Values.db.mongo_db_url}}"
          - 
            name: TLS_CERTIFICATEKEYFILE
            value: "{{.Values.db.tls_certficatekeyfile}}"
          - 
            name: TLS_CERTIFICATEKEYFILE_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "fast-api-k8s-helm.fullname" . }}
                  key: TLS_CERTIFICATEKEYFILE_PASSWORD

          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tls_certificates
          secret:
            secretName:  {{ include "fast-api-k8s-helm.fullname" . }}
